---
title: "CSB Maps"
author: "Jessica Bonnie"
date: "9/28/2017"
output: html_document
---

## Read in Shape Files and Key

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

require(raster)
require(dplyr)
require(pander)
require(leaflet)
csb.shp <- raster::shapefile("./shapefiles/CSBfinal_1.shp")
csb.shp@data$OBJECTID <- 1:nrow(csb.shp@data)

csb.key <- read.csv("./CSB_FIPS_GIS.csv")

csb.only <- csb.key %>% group_by(CSBName, OBJECTID,FID) %>% summarize(count=n()) %>% arrange(OBJECTID)


csb.ogr <- merge(csb.shp,csb.only,by="OBJECTID",all.x=TRUE)
# saveRDS(csb.ogr,file="CSBmap.rds")


print(str(csb.shp))

```

## Draw a map


```{r map}
  leaflet(csb.ogr) %>% addTiles( ) %>% addPolygons(weight = 1,label=~csb.ogr@data$CSBName)
```

## Get labels for map???

Need to combine the CSB key with the shapefiles as a **SpatialPolygonsDataFrame** in order to give it labels ? 

```{r makething}
test <- rgeos::gSimplify(csb.shp,tol=.5,topologyPreserve=TRUE)
test <- sp::SpatialPolygonsDataFrame(test,csb.shp@data)

leaflet(test) %>% addTiles() %>% addLines(weight = 1) %>% addMarkers(label = ~CSBName)
```




## Read in counties file from the census (start with 20m, lower resolution file)

```{r counties}
  # create counties ogr table from shape files from census.gov

# counties.ogr.500k <- rgdal::readOGR(dsn = path.expand('~/Downloads/cb_2016_us_county_500k/'),layer='cb_2016_us_county_500k')
#   counties.ogr.500k@data$GEOID<-as.character(counties.ogr.500k@data$GEOID)
#   counties.ogr.500k@data$rec<-1:nrow(counties.ogr.500k@data)

  # test <- rgeos::gSimplify(counties.ogr.500k,tol=.5,topologyPreserve=TRUE)
  # test <- sp::SpatialPolygonsDataFrame(test,counties.ogr.500k@data)
  # saveRDS(test,file="./data/counties_ogr_20m_gSimplify.rds")

# saveRDS(counties.ogr.500k,file="../Counties/states_ogr_500k.rds")

# counties.ogr <- readRDS("../Counties/counties_ogr_20m.rds")
# counties.ogr.500k <- readRDS("../Counties/states_ogr_500k.rds")


va.counties <- counties.ogr.500k[counties.ogr.500k$STATEFP==51,]
saveRDS(va.counties,file="../counties/va_ogr_500k.rds")

test <- union(va.counties,csb.ogr)

leaflet(test) %>% addPolylines(weight)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
